spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs_doc?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 비번

  jpa:
    hibernate:
      ddl-auto: validate

  app:
    storage:
      md-root: C:\Users\Kingdomcome\Documents\CS_DOC_DATA\md
